/**
 * Seed data constants — IDs from the OGS (Proving Grounds) set.
 * Auto-generated by generate-seed.ts — do not edit manually.
 */

// -- Set -----------------------------------------------------------------------

export const OGS_SET = {
  id: "019cf052-e002-78ef-b032-cc585ba33eb3",
  slug: "OGS",
  name: "Proving Grounds",
} as const;

// -- Cards (all 24) -----------------------------------------------------------

export const CARDS = {
  "OGS-001": {
    id: "019cf052-e00a-7256-ab8d-6e39b367029d",
    slug: "OGS-001",
    name: "Annie, Fiery",
    type: "Unit",
    domains: ["Fury"],
  },
  "OGS-002": {
    id: "019cf052-e00a-72b3-9ad6-76b7a7937ed9",
    slug: "OGS-002",
    name: "Firestorm",
    type: "Spell",
    domains: ["Fury"],
  },
  "OGS-003": {
    id: "019cf052-e009-7e7a-8ef3-3d7af480b233",
    slug: "OGS-003",
    name: "Incinerate",
    type: "Spell",
    domains: ["Fury"],
  },
  "OGS-004": {
    id: "019cf052-e00a-725a-af1a-96c66acfa59f",
    slug: "OGS-004",
    name: "Yi, Meditative",
    type: "Unit",
    domains: ["Calm"],
  },
  "OGS-005": {
    id: "019cf052-e00a-72b7-84bf-56a562e24ace",
    slug: "OGS-005",
    name: "Zephyr Sage",
    type: "Unit",
    domains: ["Calm"],
  },
  "OGS-006": {
    id: "019cf052-e00a-71e8-a89f-b0ba7ccc7bcf",
    slug: "OGS-006",
    name: "Lux, Illuminated",
    type: "Unit",
    domains: ["Mind"],
  },
  "OGS-007": {
    id: "019cf052-e00a-725d-9893-e1661bf5d66b",
    slug: "OGS-007",
    name: "Garen, Rugged",
    type: "Unit",
    domains: ["Body"],
  },
  "OGS-008": {
    id: "019cf052-e00a-72bb-b0ae-c30d1a778a6c",
    slug: "OGS-008",
    name: "Gentlemen's Duel",
    type: "Spell",
    domains: ["Body"],
  },
  "OGS-009": {
    id: "019cf052-e00a-71ee-9e47-e8d173da9445",
    slug: "OGS-009",
    name: "Yi, Honed",
    type: "Unit",
    domains: ["Body"],
  },
  "OGS-010": {
    id: "019cf052-e00a-7261-8a14-4251647a9001",
    slug: "OGS-010",
    name: "Annie, Stubborn",
    type: "Unit",
    domains: ["Chaos"],
  },
  "OGS-011": {
    id: "019cf052-e00a-72bf-9b5a-3f26d58d905b",
    slug: "OGS-011",
    name: "Flash",
    type: "Spell",
    domains: ["Chaos"],
  },
  "OGS-012": {
    id: "019cf052-e00a-71f4-816a-f90d301eb3e0",
    slug: "OGS-012",
    name: "Blast of Power",
    type: "Spell",
    domains: ["Order"],
  },
  "OGS-013": {
    id: "019cf052-e00a-7265-bbe5-fca1516a3fea",
    slug: "OGS-013",
    name: "Garen, Commander",
    type: "Unit",
    domains: ["Order"],
  },
  "OGS-014": {
    id: "019cf052-e00a-72c2-928f-ecb5b16295ff",
    slug: "OGS-014",
    name: "Lux, Crownguard",
    type: "Unit",
    domains: ["Order"],
  },
  "OGS-015": {
    id: "019cf052-e00a-71fa-922b-b2f3d4e9825e",
    slug: "OGS-015",
    name: "Recruit the Vanguard",
    type: "Spell",
    domains: ["Order"],
  },
  "OGS-016": {
    id: "019cf052-e00a-7268-b4a4-ef652da2b35c",
    slug: "OGS-016",
    name: "Vanguard Attendant",
    type: "Unit",
    domains: ["Order"],
  },
  "OGS-017": {
    id: "019cf052-e00a-72c6-ace9-ec2fc4fccb63",
    slug: "OGS-017",
    name: "Dark Child - Starter",
    type: "Legend",
    domains: ["Fury", "Chaos"],
  },
  "OGS-018": {
    id: "019cf052-e00a-71fe-aafc-9e401d229a9d",
    slug: "OGS-018",
    name: "Tibbers",
    type: "Unit",
    domains: ["Fury", "Chaos"],
  },
  "OGS-019": {
    id: "019cf052-e00a-726f-953a-9d8e4b960185",
    slug: "OGS-019",
    name: "Wuju Bladesman - Starter",
    type: "Legend",
    domains: ["Calm", "Body"],
  },
  "OGS-020": {
    id: "019cf052-e00a-72ca-8947-eb08feda6df5",
    slug: "OGS-020",
    name: "Highlander",
    type: "Spell",
    domains: ["Calm", "Body"],
  },
  "OGS-021": {
    id: "019cf052-e00a-7204-a83d-fb19eb0fe551",
    slug: "OGS-021",
    name: "Lady of Luminosity - Starter",
    type: "Legend",
    domains: ["Mind", "Order"],
  },
  "OGS-022": {
    id: "019cf052-e00a-7273-ac23-c25c9631f0ce",
    slug: "OGS-022",
    name: "Final Spark",
    type: "Spell",
    domains: ["Mind", "Order"],
  },
  "OGS-023": {
    id: "019cf052-e00a-72cd-a297-1a50d6a513f2",
    slug: "OGS-023",
    name: "Might of Demacia - Starter",
    type: "Legend",
    domains: ["Body", "Order"],
  },
  "OGS-024": {
    id: "019cf052-e00a-7394-af87-5b5f926f4b8d",
    slug: "OGS-024",
    name: "Decisive Strike",
    type: "Spell",
    domains: ["Body", "Order"],
  },
} as const;

// -- Printings (all 24) -------------------------------------------------------

export const PRINTINGS = {
  "OGS-001:epic:normal:": {
    id: "019cf052-e020-7222-b8bf-3c9fc2151abc",
    cardId: "019cf052-e00a-7256-ab8d-6e39b367029d",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-002:uncommon:normal:": {
    id: "019cf052-e01f-7f65-8d7a-a28fddcf5d61",
    cardId: "019cf052-e00a-72b3-9ad6-76b7a7937ed9",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-003:common:normal:": {
    id: "019cf052-e020-7228-9093-13d47b91b4d9",
    cardId: "019cf052-e009-7e7a-8ef3-3d7af480b233",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-004:rare:normal:": {
    id: "019cf052-e020-722c-bdb0-235e1b9d475d",
    cardId: "019cf052-e00a-725a-af1a-96c66acfa59f",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-005:uncommon:normal:": {
    id: "019cf052-e020-7230-81a8-2f652a882e3e",
    cardId: "019cf052-e00a-72b7-84bf-56a562e24ace",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-006:rare:normal:": {
    id: "019cf052-e020-7233-ace3-5d242165088c",
    cardId: "019cf052-e00a-71e8-a89f-b0ba7ccc7bcf",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-007:rare:normal:": {
    id: "019cf052-e020-7237-a5c7-7b79b22ef70b",
    cardId: "019cf052-e00a-725d-9893-e1661bf5d66b",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-008:common:normal:": {
    id: "019cf052-e020-723b-817f-7fecb7f7a0b4",
    cardId: "019cf052-e00a-72bb-b0ae-c30d1a778a6c",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-009:epic:normal:": {
    id: "019cf052-e020-723f-8a34-3913cf88e36b",
    cardId: "019cf052-e00a-71ee-9e47-e8d173da9445",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-010:rare:normal:": {
    id: "019cf052-e020-7242-be21-f7103a9b2590",
    cardId: "019cf052-e00a-7261-8a14-4251647a9001",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-011:common:normal:": {
    id: "019cf052-e020-7246-a575-1c8a1511ce0f",
    cardId: "019cf052-e00a-72bf-9b5a-3f26d58d905b",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-012:common:normal:": {
    id: "019cf052-e020-7249-9623-e1665b3d9f7c",
    cardId: "019cf052-e00a-71f4-816a-f90d301eb3e0",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-013:epic:normal:": {
    id: "019cf052-e020-724d-9342-21599b5ac222",
    cardId: "019cf052-e00a-7265-bbe5-fca1516a3fea",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-014:epic:normal:": {
    id: "019cf052-e020-7251-8d8c-e03fbf6c693a",
    cardId: "019cf052-e00a-72c2-928f-ecb5b16295ff",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-015:uncommon:normal:": {
    id: "019cf052-e020-7254-a36f-6dc08f58214c",
    cardId: "019cf052-e00a-71fa-922b-b2f3d4e9825e",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-016:common:normal:": {
    id: "019cf052-e020-7258-aadc-7ad3c1ff4972",
    cardId: "019cf052-e00a-7268-b4a4-ef652da2b35c",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-017:rare:normal:": {
    id: "019cf052-e020-7260-8b18-ea839483b30e",
    cardId: "019cf052-e00a-72c6-ace9-ec2fc4fccb63",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-018:epic:normal:": {
    id: "019cf052-e020-783d-895b-d23f38f603ce",
    cardId: "019cf052-e00a-71fe-aafc-9e401d229a9d",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-019:rare:normal:": {
    id: "019cf052-e020-7841-9998-c485c43401d5",
    cardId: "019cf052-e00a-726f-953a-9d8e4b960185",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-020:epic:normal:": {
    id: "019cf052-e020-7845-8e4b-f5eff2ceff6f",
    cardId: "019cf052-e00a-72ca-8947-eb08feda6df5",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-021:rare:normal:": {
    id: "019cf052-e020-7849-a7b7-7710d3ef280a",
    cardId: "019cf052-e00a-7204-a83d-fb19eb0fe551",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-022:epic:normal:": {
    id: "019cf052-e020-784c-a600-31246d419d4a",
    cardId: "019cf052-e00a-7273-ac23-c25c9631f0ce",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-023:rare:normal:": {
    id: "019cf052-e020-7850-9bd3-99b1768cf869",
    cardId: "019cf052-e00a-72cd-a297-1a50d6a513f2",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-024:epic:normal:": {
    id: "019cf052-e020-7853-9e72-b09d435a9362",
    cardId: "019cf052-e00a-7394-af87-5b5f926f4b8d",
    rarity: "Epic",
    finish: "normal",
  },
} as const;

// -- Convenience aliases for common test needs --------------------------------

/** A Unit card in the Fury domain (Epic rarity) */
export const CARD_FURY_UNIT = CARDS["OGS-001"];
/** A Spell card in the Fury domain (Uncommon rarity) */
export const CARD_FURY_SPELL = CARDS["OGS-002"];
/** A Unit card in the Calm domain (Rare rarity) */
export const CARD_CALM_UNIT = CARDS["OGS-004"];
/** A Unit card in the Body domain (Rare rarity) */
export const CARD_BODY_UNIT = CARDS["OGS-007"];
/** A Unit card in the Mind domain (Rare rarity) */
export const CARD_MIND_UNIT = CARDS["OGS-006"];
/** A Unit card in the Order domain (Epic rarity) */
export const CARD_ORDER_UNIT = CARDS["OGS-013"];

/** Printing for OGS-001 (Epic, normal finish) */
export const PRINTING_1 = PRINTINGS["OGS-001:epic:normal:"];
/** Printing for OGS-002 (Uncommon, normal finish) */
export const PRINTING_2 = PRINTINGS["OGS-002:uncommon:normal:"];
/** Printing for OGS-003 (Common, normal finish) */
export const PRINTING_3 = PRINTINGS["OGS-003:common:normal:"];
/** Printing for OGS-004 (Rare, normal finish) */
export const PRINTING_4 = PRINTINGS["OGS-004:rare:normal:"];

// -- Marketplace groups -------------------------------------------------------

export const MARKETPLACE_GROUPS = {
  cardmarket_6286: {
    id: "019cf052-a5f7-7fab-bea9-3935c6422a7a",
    marketplace: "cardmarket",
    groupId: 6286,
    name: "Origins",
  },
  cardmarket_6289: {
    id: "019cf052-a5f7-7faf-b822-3b2867f45e44",
    marketplace: "cardmarket",
    groupId: 6289,
    name: "Proving Grounds",
  },
  cardmarket_6322: {
    id: "019cf052-a5f7-7fb2-9418-3fc52da53faf",
    marketplace: "cardmarket",
    groupId: 6322,
    name: "Origins: Promos",
  },
  cardmarket_6399: {
    id: "019cf052-a5f7-7fb5-8a03-11e7d64c7ed1",
    marketplace: "cardmarket",
    groupId: 6399,
    name: "Spiritforged",
  },
  cardmarket_6480: {
    id: "019cf052-a5f7-7fb8-81aa-055e46ebeced",
    marketplace: "cardmarket",
    groupId: 6480,
    name: "Project K Promos",
  },
  cardmarket_6483: {
    id: "019cf052-a5f7-7fbb-a7aa-f01985bede04",
    marketplace: "cardmarket",
    groupId: 6483,
    name: "Spiritforged: Promos",
  },
  tcgplayer_24343: {
    id: "019cf052-a5f7-7fa4-8a4a-b8eae6d07948",
    marketplace: "tcgplayer",
    groupId: 24_343,
    name: "Riftbound Promotional Cards",
  },
  tcgplayer_24344: {
    id: "019cf052-a5f7-7f9b-a52a-250fb4479d20",
    marketplace: "tcgplayer",
    groupId: 24_344,
    name: "Origins",
  },
  tcgplayer_24439: {
    id: "019cf052-a5f7-7f9e-b93c-0af9b4910b23",
    marketplace: "tcgplayer",
    groupId: 24_439,
    name: "Origins: Proving Grounds",
  },
  tcgplayer_24502: {
    id: "019cf052-a5f7-7fa8-99e1-3cd2200b548d",
    marketplace: "tcgplayer",
    groupId: 24_502,
    name: "Riftbound Worlds Bundle 2025",
  },
  tcgplayer_24519: {
    id: "019cf052-a5f7-7f89-98f8-eb347444be8e",
    marketplace: "tcgplayer",
    groupId: 24_519,
    name: "Spiritforged",
  },
  tcgplayer_24528: {
    id: "019cf052-a5f7-7fa1-ad27-b0451618bb4d",
    marketplace: "tcgplayer",
    groupId: 24_528,
    name: "Riftbound Organized Play Promotional Cards",
  },
  tcgplayer_24552: {
    id: "019cf052-a5f7-7f97-afc5-5932e843ada4",
    marketplace: "tcgplayer",
    groupId: 24_552,
    name: "Riftbound Judge Promotional Cards",
  },
  tcgplayer_24560: {
    id: "019cf052-a5f7-7ef3-a786-b035a3219a7c",
    marketplace: "tcgplayer",
    groupId: 24_560,
    name: "Unleashed",
  },
} as const;

/** TCGPlayer group for OGS */
export const TCGPLAYER_OGS_GROUP = MARKETPLACE_GROUPS["tcgplayer_24439"];
/** Cardmarket group for OGS */
export const CARDMARKET_OGS_GROUP = MARKETPLACE_GROUPS["cardmarket_6289"];
