/**
 * Seed data constants — IDs from the OGS (Proving Grounds) set.
 * Auto-generated by generate-seed.ts — do not edit manually.
 */

// -- Set -----------------------------------------------------------------------

export const OGS_SET = {
  id: "019cfc3b-0369-76e1-8643-5310ac59ac33",
  slug: "OGS",
  name: "Proving Grounds",
} as const;

// -- Cards (all 24) -----------------------------------------------------------

export const CARDS = {
  "OGS-001": {
    id: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    slug: "OGS-001",
    name: "Annie, Fiery",
    type: "Unit",
    domains: ["Fury"],
  },
  "OGS-002": {
    id: "019cfc3b-038a-7e00-b828-03d838e5edab",
    slug: "OGS-002",
    name: "Firestorm",
    type: "Spell",
    domains: ["Fury"],
  },
  "OGS-003": {
    id: "019cfc3b-0389-7de9-8860-226f4c8947d8",
    slug: "OGS-003",
    name: "Incinerate",
    type: "Spell",
    domains: ["Fury"],
  },
  "OGS-004": {
    id: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    slug: "OGS-004",
    name: "Master Yi, Meditative",
    type: "Unit",
    domains: ["Calm"],
  },
  "OGS-005": {
    id: "019cfc3b-038a-7e10-b8d4-6e8b9646a975",
    slug: "OGS-005",
    name: "Zephyr Sage",
    type: "Unit",
    domains: ["Calm"],
  },
  "OGS-006": {
    id: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    slug: "OGS-006",
    name: "Lux, Illuminated",
    type: "Unit",
    domains: ["Mind"],
  },
  "OGS-007": {
    id: "019cfc3b-038a-7c30-8616-613222ef6b01",
    slug: "OGS-007",
    name: "Garen, Rugged",
    type: "Unit",
    domains: ["Body"],
  },
  "OGS-008": {
    id: "019cfc3b-038a-7e20-b240-25edfa53cbca",
    slug: "OGS-008",
    name: "Gentlemen's Duel",
    type: "Spell",
    domains: ["Body"],
  },
  "OGS-009": {
    id: "019cfc3b-038a-7abc-b43e-79b55463b059",
    slug: "OGS-009",
    name: "Master Yi, Honed",
    type: "Unit",
    domains: ["Body"],
  },
  "OGS-010": {
    id: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    slug: "OGS-010",
    name: "Annie, Stubborn",
    type: "Unit",
    domains: ["Chaos"],
  },
  "OGS-011": {
    id: "019cfc3b-038a-7e2f-a482-917692bfd498",
    slug: "OGS-011",
    name: "Flash",
    type: "Spell",
    domains: ["Chaos"],
  },
  "OGS-012": {
    id: "019cfc3b-038a-7acd-8d1e-ff0cd42a7878",
    slug: "OGS-012",
    name: "Blast of Power",
    type: "Spell",
    domains: ["Order"],
  },
  "OGS-013": {
    id: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    slug: "OGS-013",
    name: "Garen, Commander",
    type: "Unit",
    domains: ["Order"],
  },
  "OGS-014": {
    id: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    slug: "OGS-014",
    name: "Lux, Crownguard",
    type: "Unit",
    domains: ["Order"],
  },
  "OGS-015": {
    id: "019cfc3b-038a-7add-b48d-e16b7614dfda",
    slug: "OGS-015",
    name: "Recruit the Vanguard",
    type: "Spell",
    domains: ["Order"],
  },
  "OGS-016": {
    id: "019cfc3b-038a-7c63-a32a-d4ca63b2bee9",
    slug: "OGS-016",
    name: "Vanguard Attendant",
    type: "Unit",
    domains: ["Order"],
  },
  "OGS-017": {
    id: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    slug: "OGS-017",
    name: "Dark Child, Starter",
    type: "Legend",
    domains: ["Fury", "Chaos"],
  },
  "OGS-018": {
    id: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    slug: "OGS-018",
    name: "Tibbers",
    type: "Unit",
    domains: ["Fury", "Chaos"],
  },
  "OGS-019": {
    id: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    slug: "OGS-019",
    name: "Wuju Bladesman, Starter",
    type: "Legend",
    domains: ["Calm", "Body"],
  },
  "OGS-020": {
    id: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    slug: "OGS-020",
    name: "Highlander",
    type: "Spell",
    domains: ["Calm", "Body"],
  },
  "OGS-021": {
    id: "019cfc3b-038a-7aff-9f64-d915ada7e046",
    slug: "OGS-021",
    name: "Lady of Luminosity, Starter",
    type: "Legend",
    domains: ["Mind", "Order"],
  },
  "OGS-022": {
    id: "019cfc3b-038a-7c96-a595-49eecd42e4bf",
    slug: "OGS-022",
    name: "Final Spark",
    type: "Spell",
    domains: ["Mind", "Order"],
  },
  "OGS-023": {
    id: "019cfc3b-038a-7e76-9ea8-f1feb5c9d837",
    slug: "OGS-023",
    name: "Might of Demacia, Starter",
    type: "Legend",
    domains: ["Body", "Order"],
  },
  "OGS-024": {
    id: "019cfc3b-038b-7140-a819-397e9b1eb94e",
    slug: "OGS-024",
    name: "Decisive Strike",
    type: "Spell",
    domains: ["Body", "Order"],
  },
} as const;

// -- Printings (all 24) -------------------------------------------------------

export const PRINTINGS = {
  "OGS-001:epic:normal:": {
    id: "019cfc3b-03d6-74cf-adec-1dce41f631eb",
    cardId: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-001:epic:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d17a1-2723-733a-a21e-4630e4370046",
    cardId: "019cfc3b-038a-7c0c-a76c-e0a5e2f46b18",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-002:uncommon:normal:": {
    id: "019cfc3b-03d5-768e-91cf-8ac59b20fb0e",
    cardId: "019cfc3b-038a-7e00-b828-03d838e5edab",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-003:common:normal:": {
    id: "019cfc3b-03d6-74e0-bdbe-4aca898a0bbd",
    cardId: "019cfc3b-0389-7de9-8860-226f4c8947d8",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-004:rare:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d17a6-13f6-74f3-bcaa-6974580b57db",
    cardId: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-004:rare:normal:": {
    id: "019cfc3b-03d6-74f2-bcff-7bd89d0061f5",
    cardId: "019cfc3b-038a-7c1e-a8eb-57c9b27608ca",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-005:uncommon:normal:": {
    id: "019cfc3b-03d6-7502-b5c1-a9e422f91ac7",
    cardId: "019cfc3b-038a-7e10-b8d4-6e8b9646a975",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-006:rare:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1be8-3681-73b5-bf13-078b7e3c9096",
    cardId: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-006:rare:normal:": {
    id: "019cfc3b-03d6-7514-9347-be4597ff1eee",
    cardId: "019cfc3b-038a-7aab-b290-3ac99454fe0e",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-007:rare:normal:": {
    id: "019cfc3b-03d6-752a-adc5-19033009d65d",
    cardId: "019cfc3b-038a-7c30-8616-613222ef6b01",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-007:rare:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1bee-0857-793a-b76b-50b6ead8ddbb",
    cardId: "019cfc3b-038a-7c30-8616-613222ef6b01",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-008:common:normal:": {
    id: "019cfc3b-03d6-753c-9ec3-7cf48219b1e8",
    cardId: "019cfc3b-038a-7e20-b240-25edfa53cbca",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-009:epic:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d17ac-724a-732c-b83a-23cd257a74e5",
    cardId: "019cfc3b-038a-7abc-b43e-79b55463b059",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-009:epic:normal:": {
    id: "019cfc3b-03d6-754e-a4de-ca223b302965",
    cardId: "019cfc3b-038a-7abc-b43e-79b55463b059",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-010:rare:normal:": {
    id: "019cfc3b-03d6-755e-8d42-32464c0bf236",
    cardId: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-010:rare:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1bf8-97d5-79ac-929e-286838af5508",
    cardId: "019cfc3b-038a-7c41-b170-c9f989adc4a8",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-011:common:normal:": {
    id: "019cfc3b-03d6-7570-ac57-ad240fe24183",
    cardId: "019cfc3b-038a-7e2f-a482-917692bfd498",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-012:common:normal:": {
    id: "019cfc3b-03d6-7581-bf1d-f627860d73b0",
    cardId: "019cfc3b-038a-7acd-8d1e-ff0cd42a7878",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-013:epic:normal:": {
    id: "019cfc3b-03d6-7592-be7d-af8b5a85a818",
    cardId: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-013:epic:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1bfd-da4c-73d9-b2c9-a6c628b23bdd",
    cardId: "019cfc3b-038a-7c52-b7f5-683161fa2c98",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-014:epic:normal:": {
    id: "019cfc3b-03d6-75a3-90b8-c82d7afdc00a",
    cardId: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-014:epic:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1c00-e58f-73c9-a402-a822d45df1f9",
    cardId: "019cfc3b-038a-7e42-8b17-0f904fc6a78c",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-015:uncommon:normal:": {
    id: "019cfc3b-03d6-75d8-a0f7-c6fd8a35c6f9",
    cardId: "019cfc3b-038a-7add-b48d-e16b7614dfda",
    rarity: "Uncommon",
    finish: "normal",
  },
  "OGS-016:common:normal:": {
    id: "019cfc3b-03d6-75ee-922c-1e736369b5d4",
    cardId: "019cfc3b-038a-7c63-a32a-d4ca63b2bee9",
    rarity: "Common",
    finish: "normal",
  },
  "OGS-017:rare:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1c05-bf03-747d-be95-60ee1687b24b",
    cardId: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-017:rare:normal:": {
    id: "019cfc3b-03d6-7600-9bd2-f43441e40ace",
    cardId: "019cfc3b-038a-7e54-90c3-34a262a17bea",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-018:epic:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1c0b-64ab-7160-8bd6-36dfdffb1210",
    cardId: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-018:epic:normal:": {
    id: "019cfc3b-03d8-7309-9eae-0ba9ba5967f3",
    cardId: "019cfc3b-038a-7aef-b46a-dc08a7a17008",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-019:rare:normal:": {
    id: "019cfc3b-03d8-731c-8957-4f2dc4f8464f",
    cardId: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-019:rare:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1c0e-5395-709b-a44a-b9b9bc85907b",
    cardId: "019cfc3b-038a-7c85-87b3-452bea9999fb",
    rarity: "Rare",
    finish: "foil",
  },
  "OGS-020:epic:normal:": {
    id: "019cfc3b-03d8-732e-9d55-1e74ebff11dd",
    cardId: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-020:epic:foil:019d02a7-1639-7700-a279-2e6f4f6dc91c": {
    id: "019d1c11-4999-78e3-9980-2298b44d436d",
    cardId: "019cfc3b-038a-7e66-ae6d-5c57a250af7e",
    rarity: "Epic",
    finish: "foil",
  },
  "OGS-021:rare:normal:": {
    id: "019cfc3b-03d8-7340-8664-d8b5b646ef84",
    cardId: "019cfc3b-038a-7aff-9f64-d915ada7e046",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-022:epic:normal:": {
    id: "019cfc3b-03d8-7350-b433-2aee587b1912",
    cardId: "019cfc3b-038a-7c96-a595-49eecd42e4bf",
    rarity: "Epic",
    finish: "normal",
  },
  "OGS-023:rare:normal:": {
    id: "019cfc3b-03d8-7361-9a9a-915783d54e1c",
    cardId: "019cfc3b-038a-7e76-9ea8-f1feb5c9d837",
    rarity: "Rare",
    finish: "normal",
  },
  "OGS-024:epic:normal:": {
    id: "019cfc3b-03d8-7371-9e2d-f3aa5ad324a9",
    cardId: "019cfc3b-038b-7140-a819-397e9b1eb94e",
    rarity: "Epic",
    finish: "normal",
  },
} as const;

// -- Convenience aliases for common test needs --------------------------------

/** A Unit card in the Fury domain (Epic rarity) */
export const CARD_FURY_UNIT = CARDS["OGS-001"];
/** A Spell card in the Fury domain (Uncommon rarity) */
export const CARD_FURY_SPELL = CARDS["OGS-002"];
/** A Unit card in the Calm domain (Rare rarity) */
export const CARD_CALM_UNIT = CARDS["OGS-004"];
/** A Unit card in the Body domain (Rare rarity) */
export const CARD_BODY_UNIT = CARDS["OGS-007"];
/** A Unit card in the Mind domain (Rare rarity) */
export const CARD_MIND_UNIT = CARDS["OGS-006"];
/** A Unit card in the Order domain (Epic rarity) */
export const CARD_ORDER_UNIT = CARDS["OGS-013"];

/** Printing for OGS-001 (Epic, normal finish) */
export const PRINTING_1 = PRINTINGS["OGS-001:epic:normal:"];
/** Printing for OGS-002 (Uncommon, normal finish) */
export const PRINTING_2 = PRINTINGS["OGS-002:uncommon:normal:"];
/** Printing for OGS-003 (Common, normal finish) */
export const PRINTING_3 = PRINTINGS["OGS-003:common:normal:"];
/** Printing for OGS-004 (Rare, normal finish) */
export const PRINTING_4 = PRINTINGS["OGS-004:rare:normal:"];

// -- Marketplace groups -------------------------------------------------------

export const MARKETPLACE_GROUPS = {
  cardmarket_6286: {
    id: "019cfc3a-e5d3-7e7e-9497-23ee0c612850",
    marketplace: "cardmarket",
    groupId: 6286,
    name: "Origins",
  },
  cardmarket_6289: {
    id: "019cfc3a-e5d3-7e90-b462-c8bed1bf05f2",
    marketplace: "cardmarket",
    groupId: 6289,
    name: "Proving Grounds",
  },
  cardmarket_6322: {
    id: "019cfc3a-e5d3-7ea2-a7ed-d1d82f6cdea5",
    marketplace: "cardmarket",
    groupId: 6322,
    name: "Origins: Promos",
  },
  cardmarket_6399: {
    id: "019cfc3a-e5d3-7eb3-abad-5fdffa803665",
    marketplace: "cardmarket",
    groupId: 6399,
    name: "Spiritforged",
  },
  cardmarket_6480: {
    id: "019cfc3a-e5d3-7ec3-9543-f9f44e5915aa",
    marketplace: "cardmarket",
    groupId: 6480,
    name: "Project K Promos",
  },
  cardmarket_6483: {
    id: "019cfc3a-e5d3-7ed4-8999-3cd4b463f244",
    marketplace: "cardmarket",
    groupId: 6483,
    name: "Spiritforged: Promos",
  },
  cardtrader_4166: {
    id: "019d1c29-9066-737b-8946-b9e3101587c1",
    marketplace: "cardtrader",
    groupId: 4166,
    name: "Origins",
  },
  cardtrader_4167: {
    id: "019d1c29-9068-7cbc-882a-e1bcbf146596",
    marketplace: "cardtrader",
    groupId: 4167,
    name: "Promos",
  },
  cardtrader_4275: {
    id: "019d1c29-9069-7097-8252-8f3be7d4ade1",
    marketplace: "cardtrader",
    groupId: 4275,
    name: "Origins Proving Grounds",
  },
  cardtrader_4287: {
    id: "019d1c29-9069-7229-ad09-cb5eb07466c1",
    marketplace: "cardtrader",
    groupId: 4287,
    name: "Organized Play",
  },
  cardtrader_4288: {
    id: "019d1c29-9069-747a-beab-1570e3ab757b",
    marketplace: "cardtrader",
    groupId: 4288,
    name: "Judge Promos",
  },
  cardtrader_4289: {
    id: "019d1c29-9069-764c-b786-082f8c1a9840",
    marketplace: "cardtrader",
    groupId: 4289,
    name: "Arcane",
  },
  cardtrader_4299: {
    id: "019d1c29-9069-77ae-83a8-bd64449d8a9b",
    marketplace: "cardtrader",
    groupId: 4299,
    name: "Spiritforged",
  },
  cardtrader_4347: {
    id: "019d1c29-9069-7912-abde-0f84f7a0fea8",
    marketplace: "cardtrader",
    groupId: 4347,
    name: "Championship Promo",
  },
  cardtrader_4348: {
    id: "019d1c29-9069-7a79-be25-ad6ad9d2d51d",
    marketplace: "cardtrader",
    groupId: 4348,
    name: "Nexus Night Promos",
  },
  cardtrader_4349: {
    id: "019d1c29-9069-7c84-b27c-5a9bbc8498aa",
    marketplace: "cardtrader",
    groupId: 4349,
    name: "Release Event Promos",
  },
  cardtrader_4425: {
    id: "019d1c29-906a-704f-8628-feed96f41172",
    marketplace: "cardtrader",
    groupId: 4425,
    name: "Unleashed",
  },
  cardtrader_4521: {
    id: "019d1c29-906a-726f-a12f-f13b745fd5fc",
    marketplace: "cardtrader",
    groupId: 4521,
    name: "Vendetta",
  },
  cardtrader_4522: {
    id: "019d1c29-906a-74ea-b28f-1c2b80c38ccb",
    marketplace: "cardtrader",
    groupId: 4522,
    name: "Radiance",
  },
  tcgplayer_24343: {
    id: "019cfc3a-e5d3-7e5b-8dd3-6cd925320b27",
    marketplace: "tcgplayer",
    groupId: 24_343,
    name: "Riftbound Promotional Cards",
  },
  tcgplayer_24344: {
    id: "019cfc3a-e5d3-7e27-a1bc-c57dea97644a",
    marketplace: "tcgplayer",
    groupId: 24_344,
    name: "Origins",
  },
  tcgplayer_24439: {
    id: "019cfc3a-e5d3-7e38-8af3-07d1e517947c",
    marketplace: "tcgplayer",
    groupId: 24_439,
    name: "Origins: Proving Grounds",
  },
  tcgplayer_24502: {
    id: "019cfc3a-e5d3-7e6d-ad96-f51fdb4d70ba",
    marketplace: "tcgplayer",
    groupId: 24_502,
    name: "Riftbound Worlds Bundle 2025",
  },
  tcgplayer_24519: {
    id: "019cfc3a-e5d3-7df3-838e-550f1a2fd90a",
    marketplace: "tcgplayer",
    groupId: 24_519,
    name: "Spiritforged",
  },
  tcgplayer_24528: {
    id: "019cfc3a-e5d3-7e4a-bc91-dd70fab6d75c",
    marketplace: "tcgplayer",
    groupId: 24_528,
    name: "Riftbound Organized Play Promotional Cards",
  },
  tcgplayer_24552: {
    id: "019cfc3a-e5d3-7e15-8287-881760ec56ed",
    marketplace: "tcgplayer",
    groupId: 24_552,
    name: "Riftbound Judge Promotional Cards",
  },
  tcgplayer_24560: {
    id: "019cfc3a-e5d3-7c3d-96c9-dc5f89f12fba",
    marketplace: "tcgplayer",
    groupId: 24_560,
    name: "Unleashed",
  },
} as const;

/** TCGPlayer group for OGS */
export const TCGPLAYER_OGS_GROUP = MARKETPLACE_GROUPS["tcgplayer_24439"];
/** Cardmarket group for OGS */
export const CARDMARKET_OGS_GROUP = MARKETPLACE_GROUPS["cardmarket_6289"];
