version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
