// Re-export all table types from the local tables file (single source of truth).
export type {
  AdminEventAction,
  AdminEventEntityType,
  CollectionEventsTable,
  CandidateCardsTable,
  CandidatePrintingsTable,
  CardNameAliasesTable,
  CardBansTable,
  CardErrataTable,
  CardsTable,
  CardSubmissionKind,
  CardSubmissionReason,
  CardSubmissionStatus,
  CardSubmissionsTable,
  CollectionsTable,
  CopiesTable,
  Database,
  DeckCardsTable,
  DeckFoldersTable,
  DeckPlansTable,
  DeckMatchupPlansTable,
  DeckMatchupSwapsTable,
  DecksTable,
  FeatureFlagsTable,
  UserFeatureFlagsTable,
  SiteSettingsTable,
  IgnoredCandidateCardsTable,
  IgnoredCandidatePrintingsTable,
  KeywordsTable,
  MarketplaceProductPricesTable,
  PrintingImagesTable,
  PrintingsTable,
  SetsTable,
  ListEntriesTable,
  ListsTable,
  // Meta archive
  MetaEventsTable,
  MetaEventPlayersTable,
  MetaEventMatchesTable,
  MetaEventPhasesTable,
  // Meta archive catalogue sync
  UvsgamesEventsTable,
  PlayloltcgEventsTable,
  TopdeckEventsTable,
  // Meta archive source mirrors (ADR-014 rev 3)
  UvsgamesEventStandingsTable,
  UvsgamesEventPhasesTable,
  UvsgamesEventMatchesTable,
  UvsgamesDecklistsTable,
  UvsgamesDecklistCardsTable,
  PlayloltcgEventStandingsTable,
  PlayloltcgDecklistsTable,
  PlayloltcgDecklistCardsTable,
  TopdeckEventStandingsTable,
  TopdeckDecklistsTable,
  TopdeckDecklistCardsTable,
  // Meta archive overlays
  MetaEventOverlaysTable,
  MetaEventPlayerOverlaysTable,
  MetaEventPlayerOverlayCardsTable,
  // Meta archive multi-source
  MetaEventSourcesTable,
  MetaPlayerLinksTable,
  MetaSubmissionsTable,
  // Tier lists (migration 237)
  TierListCard,
  TierListRow,
  TierListsTable,
  // Preconstructed products (migration 198, ADR-015)
  ProductsTable,
  // Friend groups (migration 134, 141)
  FriendGroupCollectionSharesTable,
  FriendGroupDiscordLinksTable,
  FriendGroupInvitesTable,
  FriendGroupListSharesTable,
  FriendGroupMembersTable,
  FriendGroupsTable,
  // Organizations + tournaments umbrella (migration 166/167, ADR-033)
  OrganizationsTable,
  OverlayChannelsTable,
  // Saved creator-tool dressing (migration 242)
  StagePresetsTable,
  OrganizationMembersTable,
  TournamentsTable,
  TournamentParticipantsTable,
  PodRoundsTable,
  PodsTable,
  // Card trades (migration 143, ADR-019)
  CardTradesTable,
  // Loans (migration 195, ADR-039)
  LoansTable,
  // Deck check (migration 149, ADR-025)
  DeckCheckEntriesTable,
  DeckCheckEntryCardsTable,
  DeckCheckKeysTable,
  UserPreferencesTable,
  // Reference tables (migration 062)
  DomainsTable,
  MarkersTable,
  RaritiesTable,
  ReferenceTable,
} from "./tables.js";
