// Re-export all table types from the shared package (single source of truth).
export type {
  ActivitiesTable,
  ActivityItemsTable,
  CardSourcesTable,
  CardsTable,
  CollectionsTable,
  CopiesTable,
  Database,
  DeckCardsTable,
  DecksTable,
  FeatureFlagsTable,
  MarketplaceSnapshotsTable,
  MarketplaceSourcesTable,
  PrintingImagesTable,
  PrintingSourcesTable,
  PrintingsTable,
  SetsTable,
  SourcesTable,
  TradeListItemsTable,
  TradeListsTable,
  WishListItemsTable,
  WishListsTable,
} from "@openrift/shared/types";
