// Re-export all table types from the local tables file (single source of truth).
export type {
  CollectionEventsTable,
  CandidateCardsTable,
  CandidatePrintingsTable,
  CardNameAliasesTable,
  CardBansTable,
  CardErrataTable,
  CardsTable,
  CollectionsTable,
  CopiesTable,
  Database,
  DeckCardsTable,
  DecksTable,
  FeatureFlagsTable,
  UserFeatureFlagsTable,
  SiteSettingsTable,
  IgnoredCandidateCardsTable,
  IgnoredCandidatePrintingsTable,
  KeywordStylesTable,
  KeywordTranslationsTable,
  MarketplaceProductsTable,
  MarketplaceSnapshotsTable,
  PrintingImagesTable,
  PrintingsTable,
  SetsTable,
  TradeListItemsTable,
  TradeListsTable,
  UserPreferencesTable,
  WishListItemsTable,
  WishListsTable,
  // Reference tables (migration 062)
  DomainsTable,
  ReferenceTable,
} from "./tables.js";
