import { useLayoutEffect, useState } from "react";

import { GRID_GAP_MAX, GRID_GAP_MIN } from "@/lib/card-grid-metrics";

/**
 * Drives the measured grid below and the `SSR_RESPONSIVE_GRID_COLS` /
 * `SSR_RESPONSIVE_GRID_GAP` class strings, which `use-responsive-columns.test.ts`
 * regenerates from it.
 */
export const COLUMN_BANDS = [
  { minWidth: 0, columns: 2 },
  { minWidth: 640, columns: 3 },
  { minWidth: 768, columns: 4 },
  { minWidth: 1024, columns: 5 },
  { minWidth: 1280, columns: 6 },
  { minWidth: 1600, columns: 7 },
  { minWidth: 1920, columns: 8 },
] as const;

const MIN_CARD_WIDTH = 100;
const MAX_CARD_WIDTH = 500;

// Must match server and client to avoid a hydration mismatch on
// `style.gridTemplateColumns`; /promos SSRs this for crawlers.
const SSR_SAFE_COLUMNS = 2;

export function useResponsiveColumns(maxColumns?: number | null) {
  // useState, not a ref: the container can mount on a render after this hook
  // first ran (e.g. behind a cold-cache loading placeholder), and a ref would
  // never notify the effect below of that late mount.
  const [containerEl, setContainerEl] = useState<HTMLDivElement | null>(null);
  const [columns, setColumns] = useState(() => maxColumns ?? SSR_SAFE_COLUMNS);
  const [physicalMax, setPhysicalMax] = useState(8);
  const [physicalMin, setPhysicalMin] = useState(1);
  const [autoColumns, setAutoColumns] = useState(SSR_SAFE_COLUMNS);
  const [containerWidth, setContainerWidth] = useState(400);
  const [measured, setMeasured] = useState(false);

  useLayoutEffect(() => {
    const el = containerEl;
    if (!el) {
      return;
    }

    let prevPMax = -1;
    let prevPMin = -1;
    let prevAuto = -1;
    let prevCols = -1;
    let prevWidth = -1;
    let rafId = 0;

    const updateColumns = () => {
      const width = el.offsetWidth;
      // The gap shrinks with the card (card-grid-metrics.ts), so each bound uses
      // the gap it will actually be laid out with.
      const pMax = Math.max(
        1,
        Math.floor((width + GRID_GAP_MIN) / (MIN_CARD_WIDTH + GRID_GAP_MIN)),
      );
      const pMin = Math.max(1, Math.ceil((width + GRID_GAP_MAX) / (MAX_CARD_WIDTH + GRID_GAP_MAX)));

      const match = COLUMN_BANDS.findLast((band) => width >= band.minWidth);
      const auto = match?.columns ?? SSR_SAFE_COLUMNS;

      const cols =
        maxColumns !== undefined && maxColumns !== null
          ? Math.max(pMin, Math.min(maxColumns, pMax))
          : auto;

      const changed =
        pMax !== prevPMax ||
        pMin !== prevPMin ||
        auto !== prevAuto ||
        cols !== prevCols ||
        width !== prevWidth;
      if (!changed) {
        return;
      }

      prevPMin = pMin;
      prevPMax = pMax;
      prevAuto = auto;
      prevCols = cols;
      prevWidth = width;
      setPhysicalMax(pMax);
      setPhysicalMin(pMin);
      setAutoColumns(auto);
      setColumns(cols);
      setContainerWidth(width);
      setMeasured(true);
    };

    updateColumns();

    const observer = new ResizeObserver(() => {
      cancelAnimationFrame(rafId);
      rafId = requestAnimationFrame(updateColumns);
    });
    observer.observe(el);

    return () => {
      cancelAnimationFrame(rafId);
      observer.disconnect();
    };
  }, [maxColumns, containerEl]);

  return {
    containerRef: setContainerEl,
    containerEl,
    columns,
    physicalMax,
    physicalMin,
    autoColumns,
    containerWidth,
    measured,
  };
}

// Tailwind classes mirroring COLUMN_BANDS; apply on a grid nested in
// `@container/grid` while `measured` is false.
export const SSR_RESPONSIVE_GRID_COLS =
  "grid-cols-2 @min-[640px]/grid:grid-cols-3 @min-[768px]/grid:grid-cols-4 @min-[1024px]/grid:grid-cols-5 @min-[1280px]/grid:grid-cols-6 @min-[1600px]/grid:grid-cols-7 @min-[1920px]/grid:grid-cols-8";

// Generated by `gridGapCss(cols)`; `use-responsive-columns.test.ts`
// regenerates and compares these against the gutter constants.
export const SSR_RESPONSIVE_GRID_GAP =
  "gap-[clamp(4px,calc(4.9881cqw_-_5.7007px),22px)] @min-[640px]/grid:gap-[clamp(4px,calc(3.271cqw_-_5.6075px),22px)] @min-[768px]/grid:gap-[clamp(4px,calc(2.4334cqw_-_5.562px),22px)] @min-[1024px]/grid:gap-[clamp(4px,calc(1.9373cqw_-_5.5351px),22px)] @min-[1280px]/grid:gap-[clamp(4px,calc(1.6092cqw_-_5.5172px),22px)] @min-[1600px]/grid:gap-[clamp(4px,calc(1.3761cqw_-_5.5046px),22px)] @min-[1920px]/grid:gap-[clamp(4px,calc(1.2021cqw_-_5.4951px),22px)]";
