import { Accordion as AccordionPrimitive } from "@base-ui/react/accordion";
import type { DeckFormat, DeckResponse, DeckZone, Printing } from "@openrift/shared";
import { WellKnown, legendDisplayName } from "@openrift/shared";
import { useQuery } from "@tanstack/react-query";
import { createLazyFileRoute, useNavigate } from "@tanstack/react-router";
import {
  AlertTriangleIcon,
  CheckCircle2Icon,
  ChevronRightIcon,
  Loader2Icon,
  SearchIcon,
  UploadIcon,
  XCircleIcon,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { Heading } from "@/components/heading";
import { ImportCatalogSearch } from "@/components/import/import-catalog-search";
import { ImportRowRawFields, ImportRowShell } from "@/components/import/import-row-shell";
import {
  SectionHeader,
  SectionHeaderActions,
  SectionHeaderDescription,
  SectionHeaderGroup,
  SectionHeaderTitle,
} from "@/components/section-header";
import { Accordion, AccordionContent, AccordionItem } from "@/components/ui/accordion";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useCards } from "@/hooks/use-cards";
import { deckDetailQueryOptions, useCreateDeck, useSaveDeckCards } from "@/hooks/use-decks";
import { useDeckFormatList, useZoneOrder } from "@/hooks/use-enums";
import { useUserId } from "@/lib/auth-session";
import type { DeckMatchStatus, DeckMatchedEntry, ResolvedCard } from "@/lib/deck-import-matcher";
import { matchDeckEntries } from "@/lib/deck-import-matcher";
import type { DeckImportFormat } from "@/lib/deck-import-parsers";
import { parseDeckImportData } from "@/lib/deck-import-parsers";
import type { ImportBucket } from "@/lib/import-summary";
import { classifyBucket } from "@/lib/import-summary";
import { matchesAllTokens, searchTokens } from "@/lib/search-match";
import { SOCIAL_LINKS } from "@/lib/social-links";
import { cn } from "@/lib/utils";
import { useLocalDecksStore } from "@/stores/local-decks-store";

export const Route = createLazyFileRoute("/_app/decks/import")({
  component: DeckImportPage,
});

// Problems first, matching the collection import flow: when zone and name tie,
// surface the entries that still need attention before the resolved ones.
const STATUS_SORT_ORDER: Record<DeckMatchStatus, number> = {
  unresolved: 0,
  "needs-review": 1,
  exact: 2,
};

/** @returns Display name for sorting purposes. */
function entryDisplayName(entry: DeckMatchedEntry): string {
  return (
    entry.resolvedCard?.cardName ??
    entry.entry.cardName ??
    entry.entry.shortCode ??
    ""
  ).toLowerCase();
}

type ImportStep = "input" | "preview";

const IMPORT_PLACEHOLDERS: Record<DeckImportFormat, string> = {
  piltover: "Paste a Piltover Archive deck code...",
  text: "Legend:\n1 Card Name\n\nMainDeck:\n3 Card Name\n...",
  tts: "OGN-001-1 OGN-002-1 OGN-003-1 ...",
};

const IMPORT_DESCRIPTIONS: Record<DeckImportFormat, React.ReactNode> = {
  piltover: (
    <>
      A compact code generated by{" "}
      <a
        href="https://piltoverarchive.com"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        Piltover Archive
      </a>
      . Copy it from the deck builder&apos;s share/export button.
    </>
  ),
  text: (
    <>
      A plain text list with optional zone headers like &quot;Legend:&quot; or
      &quot;MainDeck:&quot;. One card per line as &quot;quantity name&quot;. Without zone headers,
      cards are sorted into zones automatically based on their type. Used by many deck builders,
      including{" "}
      <a
        href="https://piltoverarchive.com"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        Piltover Archive
      </a>{" "}
      and{" "}
      <a
        href="https://tcg-arena.fr/decks"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        TCG Arena
      </a>
      .
    </>
  ),
  tts: (
    <>
      A space-separated list of short codes (e.g. OGN-001) used by the{" "}
      <a
        href="https://steamcommunity.com/sharedfiles/filedetails/?id=3606647746"
        target="_blank"
        rel="noreferrer"
        className="text-foreground underline"
      >
        Tabletop Simulator mod
      </a>
      .
    </>
  ),
};

function DeckImportPage() {
  // Auth-optional (ADR-035): logged out, an import creates a browser-local deck.
  const userId = useUserId();
  const { replaceDeckId } = Route.useSearch();
  const { allPrintings } = useCards();
  const { zoneOrder, zoneLabels } = useZoneOrder();
  const { formats: deckFormats, labels: deckFormatLabels } = useDeckFormatList();
  const createDeck = useCreateDeck();
  const saveDeckCards = useSaveDeckCards();
  const navigate = useNavigate();

  const replaceDeckQuery = useQuery({
    ...deckDetailQueryOptions(userId ?? "", replaceDeckId ?? ""),
    enabled: Boolean(replaceDeckId) && Boolean(userId),
  });
  const replaceDeckName = replaceDeckQuery.data?.deck.name;
  // Replace targets a server deck, which requires a session; logged out always
  // creates a new local deck instead.
  const isReplaceMode = Boolean(replaceDeckId) && Boolean(userId);

  const [step, setStep] = useState<ImportStep>("input");
  const [rawText, setRawText] = useState("");
  const [importFormat, setImportFormat] = useState<DeckImportFormat>("text");
  const [deckName, setDeckName] = useState("Imported Deck");
  const [deckFormat, setDeckFormat] = useState<DeckFormat>(deckFormats[0]?.slug ?? "");
  const [matchedEntries, setMatchedEntries] = useState<DeckMatchedEntry[]>([]);
  const [parseWarnings, setParseWarnings] = useState<string[]>([]);
  const [skippedIndices, setSkippedIndices] = useState<Set<number>>(new Set());
  const [expandedValues, setExpandedValues] = useState<string[]>([]);
  const [isImporting, setIsImporting] = useState(false);
  const [confirmReplaceOpen, setConfirmReplaceOpen] = useState(false);

  const handleParse = (text: string) => {
    const { entries, warnings } = parseDeckImportData(text, importFormat);
    setParseWarnings(warnings);

    if (entries.length === 0) {
      return;
    }

    const matched = matchDeckEntries(entries, allPrintings);
    const zoneIndex = Object.fromEntries(zoneOrder.map((slug, index) => [slug, index]));
    const sorted = matched.toSorted((entryA, entryB) => {
      const zoneDiff = (zoneIndex[entryA.zone] ?? 99) - (zoneIndex[entryB.zone] ?? 99);
      if (zoneDiff !== 0) {
        return zoneDiff;
      }
      const nameA = entryDisplayName(entryA);
      const nameB = entryDisplayName(entryB);
      if (nameA !== nameB) {
        return nameA.localeCompare(nameB);
      }
      return STATUS_SORT_ORDER[entryA.status] - STATUS_SORT_ORDER[entryB.status];
    });
    setMatchedEntries(sorted);
    setSkippedIndices(new Set());

    // Auto-expand non-exact entries so the user sees what needs attention
    const nonExact: string[] = [];
    for (let index = 0; index < sorted.length; index++) {
      if (sorted[index].status !== "exact") {
        nonExact.push(String(index));
      }
    }
    setExpandedValues(nonExact);

    setStep("preview");
  };

  const handleResolve = (index: number, card: ResolvedCard) => {
    setMatchedEntries((prev) =>
      prev.map((entry, entryIndex) =>
        entryIndex === index
          ? {
              ...entry,
              resolvedCard: card,
              status: "exact" as DeckMatchStatus,
              zone: entry.entry.explicitZone ?? entry.zone,
            }
          : entry,
      ),
    );
  };

  const handleZoneChange = (index: number, zone: DeckZone) => {
    setMatchedEntries((prev) =>
      prev.map((entry, entryIndex) => (entryIndex === index ? { ...entry, zone } : entry)),
    );
  };

  const handleSkip = (index: number) => {
    setSkippedIndices((prev) => new Set([...prev, index]));
  };

  const handleUnskip = (index: number) => {
    setSkippedIndices((prev) => {
      const next = new Set(prev);
      next.delete(index);
      return next;
    });
  };

  const importableEntries = matchedEntries.filter(
    (entry, index) => entry.resolvedCard && !skippedIndices.has(index),
  );
  const visibleBuckets = matchedEntries
    .filter((_entry, index) => !skippedIndices.has(index))
    .map((entry) => classifyBucket(entry.status, entry.resolvedCard !== null));
  const readyCount = visibleBuckets.filter((bucket) => bucket === "ready").length;
  const toVerifyCount = visibleBuckets.filter((bucket) => bucket === "to-verify").length;
  const needsAttentionCount = visibleBuckets.filter((bucket) => bucket === "need-attention").length;
  const skippedCount = skippedIndices.size;
  const totalCards = importableEntries.reduce((sum, entry) => sum + entry.entry.quantity, 0);

  const buildCards = () => {
    // Group by cardId + zone + preferredPrintingId, summing quantities.
    // Printing-specific matches (piltover/tts short codes) become distinct
    // rows from any default-art rows of the same card.
    const cardMap = new Map<
      string,
      { cardId: string; zone: DeckZone; quantity: number; preferredPrintingId: string | null }
    >();
    for (const entry of importableEntries) {
      if (!entry.resolvedCard) {
        continue;
      }
      const preferredPrintingId = entry.resolvedCard.preferredPrintingId;
      const key = `${entry.resolvedCard.cardId}::${entry.zone}::${preferredPrintingId ?? ""}`;
      const existing = cardMap.get(key);
      if (existing) {
        existing.quantity += entry.entry.quantity;
      } else {
        cardMap.set(key, {
          cardId: entry.resolvedCard.cardId,
          zone: entry.zone,
          quantity: entry.entry.quantity,
          preferredPrintingId,
        });
      }
    }
    return [...cardMap.values()];
  };

  const executeReplace = () => {
    if (!replaceDeckId) {
      return;
    }
    const targetName = replaceDeckName ?? "deck";
    setIsImporting(true);
    saveDeckCards.mutate(
      { deckId: replaceDeckId, cards: buildCards() },
      {
        onSuccess: () => {
          toast.success(`Replaced cards in "${targetName}" with ${totalCards} cards.`);
          void navigate({ to: "/decks/$deckId", params: { deckId: replaceDeckId } });
        },
        onError: () => {
          toast.error("Failed to replace deck cards.");
          setIsImporting(false);
        },
      },
    );
  };

  const executeCreate = () => {
    const trimmedName = deckName.trim();
    if (!trimmedName) {
      toast.error("Please enter a deck name.");
      return;
    }

    setIsImporting(true);
    const cards = buildCards();

    // Logged out: build a browser-local deck instead of a server deck.
    if (!userId) {
      const localId = useLocalDecksStore.getState().createDeck(deckFormat, trimmedName);
      useLocalDecksStore.getState().setCards(localId, cards);
      toast.success(`Imported deck "${trimmedName}" with ${totalCards} cards.`);
      void navigate({ to: "/decks/$deckId", params: { deckId: localId } });
      return;
    }

    createDeck.mutate(
      { name: trimmedName, format: deckFormat },
      {
        onSuccess: (data) => {
          const deck = data as DeckResponse;
          saveDeckCards.mutate(
            { deckId: deck.id, cards },
            {
              onSuccess: () => {
                toast.success(`Imported deck "${trimmedName}" with ${totalCards} cards.`);
                void navigate({ to: "/decks/$deckId", params: { deckId: deck.id } });
              },
              onError: () => {
                toast.error("Failed to save deck cards.");
                setIsImporting(false);
              },
            },
          );
        },
        onError: () => {
          toast.error("Failed to create deck.");
          setIsImporting(false);
        },
      },
    );
  };

  const handleImport = () => {
    if (isReplaceMode) {
      setConfirmReplaceOpen(true);
      return;
    }
    executeCreate();
  };

  if (step === "input") {
    return (
      <InputStep
        rawText={rawText}
        onTextChange={setRawText}
        importFormat={importFormat}
        onImportFormatChange={setImportFormat}
        onParse={handleParse}
        parseWarnings={parseWarnings}
        replaceDeckName={isReplaceMode ? (replaceDeckName ?? "") : undefined}
      />
    );
  }

  return (
    <>
      <PreviewStep
        matchedEntries={matchedEntries}
        allPrintings={allPrintings}
        parseWarnings={parseWarnings}
        skippedIndices={skippedIndices}
        expandedValues={expandedValues}
        deckName={deckName}
        deckFormat={deckFormat}
        deckFormats={deckFormats}
        deckFormatLabels={deckFormatLabels}
        zoneOrder={zoneOrder}
        zoneLabels={zoneLabels}
        readyCount={readyCount}
        toVerifyCount={toVerifyCount}
        needsAttentionCount={needsAttentionCount}
        importableCount={importableEntries.length}
        skippedCount={skippedCount}
        totalCards={totalCards}
        isImporting={isImporting}
        replaceDeckName={isReplaceMode ? (replaceDeckName ?? "") : undefined}
        onResolve={handleResolve}
        onZoneChange={handleZoneChange}
        onSkip={handleSkip}
        onUnskip={handleUnskip}
        onExpandedValuesChange={setExpandedValues}
        onDeckNameChange={setDeckName}
        onDeckFormatChange={setDeckFormat}
        onImport={handleImport}
        onBack={() => setStep("input")}
      />
      <AlertDialog open={confirmReplaceOpen} onOpenChange={setConfirmReplaceOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Replace deck contents?</AlertDialogTitle>
            <AlertDialogDescription>
              This will remove all existing cards in &ldquo;{replaceDeckName ?? "this deck"}&rdquo;
              and replace them with the {totalCards} imported {totalCards === 1 ? "card" : "cards"}.
              The deck&apos;s name and format are kept.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={() => {
                setConfirmReplaceOpen(false);
                executeReplace();
              }}
            >
              Replace
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}

// ---------------------------------------------------------------------------
// Step 1: Input
// ---------------------------------------------------------------------------

function InputStep({
  rawText,
  onTextChange,
  importFormat,
  onImportFormatChange,
  onParse,
  parseWarnings,
  replaceDeckName,
}: {
  rawText: string;
  onTextChange: (text: string) => void;
  importFormat: DeckImportFormat;
  onImportFormatChange: (format: DeckImportFormat) => void;
  onParse: (text: string) => void;
  parseWarnings: string[];
  replaceDeckName?: string;
}) {
  const isReplaceMode = replaceDeckName !== undefined;
  return (
    <div className="mx-auto max-w-2xl space-y-6 px-4 py-6">
      <div>
        <Heading level={2}>{isReplaceMode ? "Replace deck contents" : "Import Deck"}</Heading>
        <p className="text-muted-foreground text-sm">
          {isReplaceMode ? (
            <>
              Paste a text list, deck code, or TTS string to replace the cards in
              {replaceDeckName ? (
                <>
                  {" "}
                  <strong className="text-foreground">&ldquo;{replaceDeckName}&rdquo;</strong>
                </>
              ) : (
                " this deck"
              )}
              . The deck&apos;s name and format are kept.
            </>
          ) : (
            <>
              Paste a text list, deck code, or TTS string to import a deck. Want another format
              supported?{" "}
              <a
                href={SOCIAL_LINKS.githubIssues}
                target="_blank"
                rel="noreferrer"
                className="text-foreground underline"
              >
                Open a GitHub issue
              </a>
              .
            </>
          )}
        </p>
      </div>

      <Tabs
        value={importFormat}
        onValueChange={(value) => onImportFormatChange(value as DeckImportFormat)}
      >
        <TabsList>
          <TabsTrigger value="text">Text</TabsTrigger>
          <TabsTrigger value="piltover">Deck Code</TabsTrigger>
          <TabsTrigger value="tts">TTS</TabsTrigger>
        </TabsList>

        <TabsContent value={importFormat}>
          <div className="space-y-3">
            <p className="text-muted-foreground text-sm">{IMPORT_DESCRIPTIONS[importFormat]}</p>
            <Textarea
              value={rawText}
              onChange={(event) => onTextChange(event.target.value)}
              placeholder={IMPORT_PLACEHOLDERS[importFormat]}
              className={cn(
                "font-mono text-xs",
                importFormat === "piltover" ? "min-h-[120px]" : "min-h-[320px]",
              )}
            />

            <div className="flex items-center gap-3">
              <Button onClick={() => onParse(rawText)} disabled={rawText.trim().length === 0}>
                <UploadIcon className="mr-2 size-4" />
                Parse
              </Button>
            </div>
          </div>
        </TabsContent>
      </Tabs>

      {parseWarnings.length > 0 && (
        <Alert variant="destructive">
          <AlertDescription>
            {parseWarnings.map((warning) => (
              <p key={warning}>{warning}</p>
            ))}
          </AlertDescription>
        </Alert>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Step 2: Preview
// ---------------------------------------------------------------------------

function PreviewStep({
  matchedEntries,
  allPrintings,
  parseWarnings,
  skippedIndices,
  expandedValues,
  deckName,
  deckFormat,
  deckFormats,
  deckFormatLabels,
  zoneOrder,
  zoneLabels,
  readyCount,
  toVerifyCount,
  needsAttentionCount,
  importableCount,
  skippedCount,
  totalCards,
  isImporting,
  replaceDeckName,
  onResolve,
  onZoneChange,
  onSkip,
  onUnskip,
  onExpandedValuesChange,
  onDeckNameChange,
  onDeckFormatChange,
  onImport,
  onBack,
}: {
  matchedEntries: DeckMatchedEntry[];
  allPrintings: Printing[];
  parseWarnings: string[];
  skippedIndices: Set<number>;
  expandedValues: string[];
  deckName: string;
  deckFormat: DeckFormat;
  deckFormats: { slug: string; label: string }[];
  deckFormatLabels: Record<string, string>;
  zoneOrder: DeckZone[];
  zoneLabels: Record<DeckZone, string>;
  readyCount: number;
  toVerifyCount: number;
  needsAttentionCount: number;
  importableCount: number;
  skippedCount: number;
  totalCards: number;
  isImporting: boolean;
  replaceDeckName?: string;
  onResolve: (index: number, card: ResolvedCard) => void;
  onZoneChange: (index: number, zone: DeckZone) => void;
  onSkip: (index: number) => void;
  onUnskip: (index: number) => void;
  onExpandedValuesChange: (values: string[]) => void;
  onDeckNameChange: (name: string) => void;
  onDeckFormatChange: (format: DeckFormat) => void;
  onImport: () => void;
  onBack: () => void;
}) {
  const isReplaceMode = replaceDeckName !== undefined;
  const canImport = importableCount > 0 && (isReplaceMode || deckName.trim().length > 0);

  return (
    <div className="mx-auto max-w-3xl space-y-4 px-4 py-6">
      <SectionHeader>
        <SectionHeaderGroup>
          <SectionHeaderTitle>
            {isReplaceMode ? "Replace Preview" : "Import Preview"}
          </SectionHeaderTitle>
          <SectionHeaderDescription>
            {matchedEntries.length} card{matchedEntries.length === 1 ? "" : "s"} parsed
            {isReplaceMode && replaceDeckName ? (
              <>
                {" "}
                — replacing contents of{" "}
                <strong className="text-foreground">&ldquo;{replaceDeckName}&rdquo;</strong>
              </>
            ) : null}
          </SectionHeaderDescription>
        </SectionHeaderGroup>
        <SectionHeaderActions>
          <Button variant="outline" size="sm" onClick={onBack}>
            Back
          </Button>
        </SectionHeaderActions>
      </SectionHeader>

      {/* Entry list */}
      <Accordion
        multiple
        value={expandedValues}
        onValueChange={(value) => onExpandedValuesChange(value as string[])}
        className="divide-border divide-y rounded-md border"
      >
        {matchedEntries.map((entry, index) => (
          <DeckImportEntryRow
            key={`${entry.entry.shortCode ?? entry.entry.cardName ?? ""}-${entry.zone}-${index}`}
            entry={entry}
            allPrintings={allPrintings}
            index={index}
            zoneOrder={zoneOrder}
            zoneLabels={zoneLabels}
            isSkipped={skippedIndices.has(index)}
            onResolve={onResolve}
            onZoneChange={onZoneChange}
            onSkip={onSkip}
            onUnskip={onUnskip}
          />
        ))}
      </Accordion>

      {/* Parse warnings */}
      {parseWarnings.length > 0 && (
        <Alert variant="warning">
          <AlertTitle>
            {parseWarnings.length} warning{parseWarnings.length === 1 ? "" : "s"} while parsing
          </AlertTitle>
          <AlertDescription>
            {parseWarnings.map((warning) => (
              <p key={warning}>{warning}</p>
            ))}
          </AlertDescription>
        </Alert>
      )}

      {/* Summary + deck options + import button */}
      <div className="bg-muted/50 space-y-4 rounded-md border p-4">
        <div className="flex flex-wrap items-center gap-2 text-sm">
          <Badge variant="success">{readyCount} ready</Badge>
          {toVerifyCount > 0 && <Badge variant="warning">{toVerifyCount} to verify</Badge>}
          {needsAttentionCount > 0 && (
            <Badge variant="destructive">{needsAttentionCount} need attention</Badge>
          )}
          {skippedCount > 0 && <Badge variant="ghost">{skippedCount} skipped</Badge>}
        </div>

        {toVerifyCount > 0 && (
          <p className="text-muted-foreground text-sm">
            We picked a best guess for {toVerifyCount} {toVerifyCount === 1 ? "card" : "cards"}{" "}
            (marked <span className="text-amber-600 dark:text-amber-400">to verify</span>). They
            will import as-is, so open each one to confirm the card if it matters.
          </p>
        )}

        {needsAttentionCount > 0 && (
          <p className="text-muted-foreground text-sm">
            Having trouble importing?{" "}
            <a
              href={SOCIAL_LINKS.githubIssues}
              target="_blank"
              rel="noreferrer"
              className="text-foreground underline"
            >
              Open a GitHub issue
            </a>{" "}
            and we&apos;ll take a look.
          </p>
        )}

        <div className="flex flex-wrap items-end gap-3">
          {!isReplaceMode && (
            <>
              <div className="space-y-1.5">
                <Label htmlFor="preview-deck-name">Deck name</Label>
                <Input
                  id="preview-deck-name"
                  value={deckName}
                  onChange={(event) => onDeckNameChange(event.target.value)}
                  className="w-[200px]"
                />
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="preview-deck-format">Format</Label>
                <Select
                  value={deckFormat}
                  onValueChange={(value) => {
                    if (value !== null) {
                      onDeckFormatChange(value);
                    }
                  }}
                >
                  <SelectTrigger id="preview-deck-format" className="mb-0 w-[140px]">
                    <SelectValue>{(value: string) => deckFormatLabels[value] ?? value}</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {deckFormats.map((entry) => (
                      <SelectItem key={entry.slug} value={entry.slug}>
                        {entry.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </>
          )}

          <Button
            variant={isReplaceMode ? "destructive" : "default"}
            onClick={onImport}
            disabled={!canImport || isImporting}
          >
            {isImporting ? (
              <>
                <Loader2Icon className="mr-2 size-4 animate-spin" />
                {isReplaceMode ? "Replacing..." : "Importing..."}
              </>
            ) : isReplaceMode ? (
              <>
                Replace with {totalCards} {totalCards === 1 ? "card" : "cards"}
              </>
            ) : (
              <>
                Import {totalCards} {totalCards === 1 ? "card" : "cards"}
              </>
            )}
          </Button>
          {needsAttentionCount > 0 && !isImporting && (
            <span className="text-muted-foreground text-sm">
              (skips {needsAttentionCount} unmatched)
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Single entry row
// ---------------------------------------------------------------------------

const BUCKET_CONFIG: Record<ImportBucket, { icon: React.ElementType; className: string }> = {
  ready: { icon: CheckCircle2Icon, className: "text-emerald-600 dark:text-emerald-400" },
  "to-verify": { icon: AlertTriangleIcon, className: "text-amber-600 dark:text-amber-400" },
  "need-attention": { icon: XCircleIcon, className: "text-red-600 dark:text-red-400" },
};

function DeckImportEntryRow({
  entry,
  allPrintings,
  index,
  zoneOrder,
  zoneLabels,
  isSkipped,
  onResolve,
  onZoneChange,
  onSkip,
  onUnskip,
}: {
  entry: DeckMatchedEntry;
  allPrintings: Printing[];
  index: number;
  zoneOrder: DeckZone[];
  zoneLabels: Record<DeckZone, string>;
  isSkipped: boolean;
  onResolve: (index: number, card: ResolvedCard) => void;
  onZoneChange: (index: number, zone: DeckZone) => void;
  onSkip: (index: number) => void;
  onUnskip: (index: number) => void;
}) {
  const [showSearch, setShowSearch] = useState(false);
  const { icon: StatusIcon, className: statusColor } =
    BUCKET_CONFIG[classifyBucket(entry.status, entry.resolvedCard !== null)];
  const rawFieldEntries = Object.entries(entry.entry.rawFields);
  const displayName =
    entry.resolvedCard?.cardName ?? entry.entry.cardName ?? entry.entry.shortCode ?? "Unknown";

  return (
    <AccordionItem
      value={String(index)}
      className={cn("not-last:border-b-0", isSkipped && "opacity-40")}
    >
      <ImportRowShell
        chevron={
          <AccordionPrimitive.Header className="flex">
            <AccordionPrimitive.Trigger
              className="group text-muted-foreground hover:text-foreground shrink-0 outline-none"
              disabled={rawFieldEntries.length === 0}
              aria-label="Toggle raw fields"
            >
              <ChevronRightIcon className="size-4 transition-transform group-data-[panel-open]:rotate-90" />
            </AccordionPrimitive.Trigger>
          </AccordionPrimitive.Header>
        }
        statusIcon={<StatusIcon className={cn("size-4 shrink-0", statusColor)} />}
        quantity={entry.entry.quantity}
        code={entry.entry.shortCode}
        name={displayName}
        nameSuffix={zoneLabels[entry.zone]}
        actions={
          <>
            {entry.suggestedName && (
              <span className="text-muted-foreground text-xs">
                Did you mean <em>{entry.suggestedName}</em>?
              </span>
            )}
            {showSearch ? (
              <CardSearch
                allPrintings={allPrintings}
                onSelect={(card) => {
                  onResolve(index, card);
                  setShowSearch(false);
                }}
              />
            ) : null}
            <Button
              variant="ghost"
              size="xs"
              onClick={() => setShowSearch(!showSearch)}
              aria-label={showSearch ? "Close search" : "Search catalog"}
            >
              {showSearch ? (
                <XCircleIcon className="size-3.5" />
              ) : (
                <SearchIcon className="size-3.5" />
              )}
            </Button>
            <ZonePicker
              zone={entry.zone}
              zoneOrder={zoneOrder}
              zoneLabels={zoneLabels}
              onZoneChange={(zone) => onZoneChange(index, zone)}
            />
            {isSkipped ? (
              <Button variant="ghost" size="xs" onClick={() => onUnskip(index)}>
                Unskip
              </Button>
            ) : (
              <Button variant="ghost" size="xs" onClick={() => onSkip(index)}>
                Skip
              </Button>
            )}
          </>
        }
      />
      {rawFieldEntries.length > 0 && (
        <AccordionContent className="bg-muted/30 border-border border-t px-4 py-2">
          <ImportRowRawFields entries={rawFieldEntries} />
        </AccordionContent>
      )}
    </AccordionItem>
  );
}

// ---------------------------------------------------------------------------
// Zone picker
// ---------------------------------------------------------------------------

function ZonePicker({
  zone,
  zoneOrder,
  zoneLabels,
  onZoneChange,
}: {
  zone: DeckZone;
  zoneOrder: DeckZone[];
  zoneLabels: Record<DeckZone, string>;
  onZoneChange: (zone: DeckZone) => void;
}) {
  // Overflow is not user-assignable
  const assignableZones = zoneOrder.filter((zoneSlug) => zoneSlug !== WellKnown.deckZone.OVERFLOW);

  return (
    <Select
      value={zone}
      onValueChange={(value) => onZoneChange(value as DeckZone)}
      items={Object.fromEntries(assignableZones.map((zoneKey) => [zoneKey, zoneLabels[zoneKey]]))}
    >
      <SelectTrigger size="sm" className="h-7 w-auto text-xs">
        <SelectValue />
      </SelectTrigger>
      <SelectContent className="w-auto">
        {assignableZones.map((zoneKey) => (
          <SelectItem key={zoneKey} value={zoneKey} className="py-1.5">
            {zoneLabels[zoneKey]}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// ---------------------------------------------------------------------------
// Card search (for correction UI)
// ---------------------------------------------------------------------------

const MAX_SEARCH_RESULTS = 20;

function CardSearch({
  allPrintings,
  onSelect,
}: {
  allPrintings: Printing[];
  onSelect: (card: ResolvedCard) => void;
}) {
  return (
    <ImportCatalogSearch<ResolvedCard>
      ariaLabel="Search cards"
      placeholder="Search cards..."
      getResults={(query) => deduplicateToCards(allPrintings, query).slice(0, MAX_SEARCH_RESULTS)}
      getKey={(card) => card.cardId}
      renderItem={(card) => (
        <>
          <span className="truncate font-medium">{card.cardName}</span>
          <span className="text-muted-foreground shrink-0">{card.shortCode}</span>
        </>
      )}
      onSelect={onSelect}
    />
  );
}

/**
 * Filters printings by query and deduplicates to unique cards.
 * @returns ResolvedCard array with one entry per unique card.
 */
function deduplicateToCards(allPrintings: Printing[], query: string): ResolvedCard[] {
  const tokens = searchTokens(query);
  if (tokens.length === 0) {
    return [];
  }
  const seen = new Set<string>();
  const results: ResolvedCard[] = [];

  for (const printing of allPrintings) {
    if (seen.has(printing.cardId)) {
      continue;
    }
    // Match the colloquial Legend name too ("Azir, Emperor of the Sands"), and
    // surface it as the display name so the dropdown reads like the rest of the app.
    const displayName = legendDisplayName(printing.card);
    if (matchesAllTokens(tokens, displayName, printing.shortCode)) {
      seen.add(printing.cardId);
      results.push({
        cardId: printing.cardId,
        cardName: displayName,
        cardType: printing.card.type,
        superTypes: printing.card.superTypes,
        domains: printing.card.domains,
        shortCode: printing.shortCode,
        preferredPrintingId: null,
      });
    }
  }

  return results;
}
