#!/usr/bin/env bash
# Regenerate nginx/cloudflare-realip.conf from Cloudflare's published ranges.
#
# The generated file is committed to the repo and included by the host nginx
# configs (openrift.conf, preview.openrift.conf) so `real_ip_header
# CF-Connecting-IP` is only trusted for connections that actually come from
# Cloudflare. Cloudflare changes these ranges rarely; re-run this script when
# https://www.cloudflare.com/ips/ announces an update, commit the diff, then
# `git pull` + `nginx -t` + reload on the VPS (same flow as any nginx change).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/nginx/cloudflare-realip.conf"

v4="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v6)"

if [[ -z "$v4" || -z "$v6" ]]; then
  echo "error: empty response from cloudflare.com/ips" >&2
  exit 1
fi

# Every line must look like an IPv4 or IPv6 CIDR — refuse to write anything
# else into a file that nginx includes as trusted-proxy configuration.
while IFS= read -r line; do
  if [[ ! "$line" =~ ^[0-9a-fA-F:./]+/[0-9]+$ ]]; then
    echo "error: unexpected line in Cloudflare IP list: $line" >&2
    exit 1
  fi
done <<<"$v4"$'\n'"$v6"

{
  echo "# Cloudflare IP ranges trusted for real_ip_header CF-Connecting-IP."
  echo "# Generated by scripts/update-cloudflare-ips.sh from"
  echo "# https://www.cloudflare.com/ips-v4 and /ips-v6 — do not edit by hand."
  while IFS= read -r line; do echo "set_real_ip_from $line;"; done <<<"$v4"
  while IFS= read -r line; do echo "set_real_ip_from $line;"; done <<<"$v6"
} >"$out.tmp"
mv "$out.tmp" "$out"

echo "wrote $out ($(grep -c '^set_real_ip_from' "$out") ranges)"
