// oxlint-disable import/no-nodejs-modules -- build-time Node script, never bundled
// Vendors flag-icons SVGs into apps/web/public/images/flags/ as small WebP.
// Run under Node, never Bun: sharp 0.35.3 under Bun corrupts one-off WebP
// encodes with row ghosting.
//
//   node scripts/vendor-flags.mjs

import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

import sharp from "sharp";

const WIDTH = 96;
const HEIGHT = 72;

const ALPHA_2_SVG = /^[a-z]{2}\.svg$/u;

const root = execFileSync("git", ["rev-parse", "--show-toplevel"]).toString().trim();
// flag-icons is pinned in apps/web; bun's isolated linker keeps it out of
// the root node_modules.
const require = createRequire(join(root, "apps/web/package.json"));
const source = join(dirname(require.resolve("flag-icons/package.json")), "flags/4x3");
const dest = join(root, "apps/web/public/images/flags");

rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });

const files = readdirSync(source).filter((file) => ALPHA_2_SVG.test(file));
const codes = [];
for (const file of files) {
  const code = file.slice(0, -4);
  // librsvg rasterizes at the SVG's own tiny viewBox without a high density
  // set first, so a downscale-only pass comes out mushy.
  await sharp(join(source, file), { density: 600 })
    .resize(WIDTH, HEIGHT, { fit: "fill" })
    .webp({ quality: 90, effort: 6 })
    .toFile(join(dest, `${code}.webp`));
  codes.push(code);
}

// Emitted so a country with no vendored flag renders its code badge, never a 404.
const list = codes
  .toSorted()
  .map((code) => `  "${code}",`)
  .join("\n");
writeFileSync(
  join(root, "apps/web/src/lib/flag-codes.ts"),
  `// Generated by scripts/vendor-flags.mjs — do not edit.
/** The alpha-2 codes \`public/images/flags/\` holds an image for. */
export const FLAG_CODES: ReadonlySet<string> = new Set([
${list}
]);
`,
);

console.log(`vendored ${codes.length} flags into ${dest}`);
