import type { EmbedBank } from "@openrift/shared/scan";
import { decodeEmbedBank } from "@openrift/shared/scan";

export interface CardLabel {
  name: string;
  code: string;
  language: string;
  /** cards.type — selects the measured text band for printing disambiguation. */
  type?: string;
}

export interface LoadedScanBank {
  bank: EmbedBank;
  /** Artwork identity per key; printings of one artwork share it. */
  artKeys: Map<string, string>;
  labels: Record<string, CardLabel>;
  bytes: number;
}

let cached: Promise<LoadedScanBank> | null = null;

/**
 * Fetch the precomputed embedding bank and its label table.
 *
 * Both files are generated by `bun scripts/scan/export-index.ts` and are not
 * committed, so a fresh checkout has to run that once before the scan page
 * works. Matching happens entirely on the device: the whole catalogue's
 * embeddings are about 2.3 MB, far cheaper to send once than a round trip per
 * frame.
 *
 * @returns The decoded bank, cached for the lifetime of the page.
 */
export async function loadScanBank(bankUrl: string, labelsUrl: string): Promise<LoadedScanBank> {
  cached ??= (async () => {
    const [bankResponse, labelResponse] = await Promise.all([fetch(bankUrl), fetch(labelsUrl)]);
    if (!bankResponse.ok) {
      throw new Error(
        `could not load the scan bank from ${bankUrl} (in dev, run: bun scripts/scan/export-index.ts)`,
      );
    }
    const buffer = await bankResponse.arrayBuffer();
    const labels = labelResponse.ok
      ? ((await labelResponse.json()) as Record<string, CardLabel>)
      : {};
    const { bank, artKeys } = decodeEmbedBank(buffer);
    return { bank, artKeys, labels, bytes: buffer.byteLength };
  })();
  try {
    return await cached;
  } catch (error) {
    // A failed download must not poison the page until reload: clear the slot
    // so the next mount retries.
    cached = null;
    throw error;
  }
}

/**
 * Human-readable name for a matched key.
 *
 * @returns The card name and printing code, or a short key when unlabelled.
 */
export function describeKey(labels: Record<string, CardLabel>, key: string): string {
  const label = labels[key];
  return label ? `${label.name} (${label.code} ${label.language})` : `unknown ${key.slice(0, 8)}`;
}
