import type { CardEmbedder } from "@openrift/shared/scan";
import { EMBED_IMAGE_SIZE } from "@openrift/shared/scan";
// The ONNX runtime loads its WASM binary at runtime from a URL. Importing the
// file through Vite gives it a hashed asset URL so it is cached and versioned
// with the bundle instead of needing a copy in public/.
import ortWasmMjsUrl from "onnxruntime-web/ort-wasm-simd-threaded.mjs?url";
import ortWasmUrl from "onnxruntime-web/ort-wasm-simd-threaded.wasm?url";

import { fetchWithProgress } from "@/lib/fetch-progress";

let cached: Promise<CardEmbedder> | null = null;
// Single slot, latest caller wins: the load runs once per page, but the hook
// can remount (strict mode, navigation) while the download is in flight and
// the fresh mount's callback is the one that should keep painting.
let progressListener: ((loaded: number, total: number) => void) | null = null;

/**
 * Load onnxruntime-web and the MobileCLIP-S0 vision tower, once per page.
 *
 * The model file is generated by `bun scripts/scan/export-index.ts` (models are
 * never committed). The WASM execution provider is the only one used: WebGPU is
 * broken on iOS under onnxruntime-web, and at batch 4 the dispatch overhead
 * outweighs the compute anyway.
 *
 * @returns The injected encoder the shared scan session runs on.
 */
export async function loadScanEmbedder(
  onProgress?: (loaded: number, total: number) => void,
): Promise<CardEmbedder> {
  if (onProgress) {
    progressListener = onProgress;
  }
  cached ??= (async () => {
    const ort = await import("onnxruntime-web/wasm");
    ort.env.wasm.wasmPaths = { wasm: ortWasmUrl, mjs: ortWasmMjsUrl };
    // Keep inference off the main thread: without the proxy every forward pass
    // blocks the UI for its full duration (1-2 s per frame on a phone). Threads
    // only engage under cross-origin isolation (COOP/COEP, set by the dev
    // server behind DEV_HTTPS); onnxruntime clamps to 1 thread without it.
    // Dev A/B knobs: ?ortThreads=N and ?ortProxy=0 override the defaults so
    // thread scaling can be measured on a phone without an edit-reload cycle.
    const params = new URLSearchParams(globalThis.location?.search ?? "");
    const threadsOverride = Number(params.get("ortThreads"));
    ort.env.wasm.proxy = params.get("ortProxy") !== "0";
    ort.env.wasm.numThreads =
      threadsOverride > 0 ? threadsOverride : Math.min(4, navigator.hardwareConcurrency || 1);
    console.log(
      `[scan] ort init: numThreads ${ort.env.wasm.numThreads} proxy ${ort.env.wasm.proxy}` +
        ` crossOriginIsolated ${globalThis.crossOriginIsolated === true}`,
    );

    const model = await fetchWithProgress(
      "/scan-encoder.onnx",
      (loaded, total) => progressListener?.(loaded, total),
      "scan-encoder.onnx is missing. Run: bun scripts/scan/export-index.ts",
    );
    const session = await ort.InferenceSession.create(model, {
      executionProviders: ["wasm"],
    });

    // Self-benchmark: one frame's worth of encoder work (4 candidates x 4
    // rotations) on deterministic input, twice — the first pass includes
    // session warmup, the second is the steady-state per-frame cost. Prints to
    // the piped console so phone thread scaling can be read from the terminal.
    const benchBatch = 16;
    const benchInput = new Float32Array(benchBatch * 3 * EMBED_IMAGE_SIZE * EMBED_IMAGE_SIZE);
    for (let pass = 0; pass < 2; pass++) {
      const benchStart = performance.now();
      await session.run({
        pixel_values: new ort.Tensor("float32", new Float32Array(benchInput), [
          benchBatch,
          3,
          EMBED_IMAGE_SIZE,
          EMBED_IMAGE_SIZE,
        ]),
      });
      console.log(
        `[scan] ort bench: batch${benchBatch} pass ${pass} ${(performance.now() - benchStart).toFixed(0)}ms`,
      );
    }

    return async (pixels, count) => {
      // The staging tensor is sized for a full batch; a short final chunk must
      // be handed over trimmed or the shape and the data length disagree. This
      // must be a copy (`slice`), not a view: the proxy worker receives the
      // tensor via postMessage transfer, which detaches the underlying
      // ArrayBuffer — a subarray view would hand over (and kill) the session's
      // reusable staging buffer on the first frame.
      const slice = pixels.slice(0, count * 3 * EMBED_IMAGE_SIZE * EMBED_IMAGE_SIZE);
      const output = await session.run({
        pixel_values: new ort.Tensor("float32", slice, [
          count,
          3,
          EMBED_IMAGE_SIZE,
          EMBED_IMAGE_SIZE,
        ]),
      });
      return output.image_embeds.data as Float32Array;
    };
  })();
  try {
    return await cached;
  } catch (error) {
    // A failed forty-megabyte download must not poison the page until reload:
    // clear the slot so the next mount retries.
    cached = null;
    throw error;
  }
}
