import type { CardEmbedder } from "@openrift/shared/scan";
import { EMBED_IMAGE_SIZE } from "@openrift/shared/scan";
// The ONNX runtime loads its WASM binary at runtime from a URL. Importing the
// file through Vite gives it a hashed asset URL so it is cached and versioned
// with the bundle instead of needing a copy in public/.
import ortWasmMjsUrl from "onnxruntime-web/ort-wasm-simd-threaded.mjs?url";
import ortWasmUrl from "onnxruntime-web/ort-wasm-simd-threaded.wasm?url";

import { fetchWithProgress } from "@/lib/fetch-progress";

let cached: Promise<CardEmbedder> | null = null;
// Single slot, latest caller wins: the load runs once per page, but the hook
// can remount (strict mode, navigation) while the download is in flight and
// the fresh mount's callback is the one that should keep painting.
let progressListener: ((loaded: number, total: number) => void) | null = null;
// Steady-state encoder cost from the init self-bench. Zero until measured.
let embedMsPerImage = 0;

/**
 * Encoder cost above which a device counts as too slow for live scanning.
 *
 * A lock is a 3-frame agreeing run and a frame costs roughly 2.5x the
 * per-image encoder time (detect, verify and preprocessing scale with the
 * same silicon — iPhone 15 Pro Max ~85 ms/image and 0.5 s locks, Pixel 1
 * ~920 ms/image and 8-12 s locks). ~250 ms/image is where the predicted lock
 * crosses the 2 s bar (user decision 2026-07-27); the same threshold turns on
 * the engine's slow-device profile.
 */
export const SLOW_DEVICE_EMBED_MS = 250;

/**
 * The measured per-image encoder cost on this device, from the init
 * self-bench.
 *
 * @returns Milliseconds per image, or 0 before the embedder has loaded.
 */
export function measuredEmbedMsPerImage(): number {
  return embedMsPerImage;
}

/**
 * Load onnxruntime-web and the MobileCLIP-S0 vision tower, once per page.
 *
 * The model file is generated by `bun scripts/scan/export-index.ts` (models are
 * never committed). The WASM execution provider is the only one used: WebGPU is
 * broken on iOS under onnxruntime-web, and at batch 4 the dispatch overhead
 * outweighs the compute anyway.
 *
 * @returns The injected encoder the shared scan session runs on.
 */
export async function loadScanEmbedder(
  modelUrl: string,
  onProgress?: (loaded: number, total: number) => void,
): Promise<CardEmbedder> {
  if (onProgress) {
    progressListener = onProgress;
  }
  cached ??= (async () => {
    const ort = await import("onnxruntime-web/wasm");
    ort.env.wasm.wasmPaths = { wasm: ortWasmUrl, mjs: ortWasmMjsUrl };
    // Keep inference off the main thread: without the proxy every forward pass
    // blocks the UI for its full duration (1-2 s per frame on a phone). Threads
    // only engage under cross-origin isolation (COOP/COEP, set by the dev
    // server behind DEV_HTTPS); onnxruntime clamps to 1 thread without it.
    // Dev A/B knobs: ?ortThreads=N and ?ortProxy=0 override the defaults so
    // thread scaling can be measured on a phone without an edit-reload cycle.
    const params = new URLSearchParams(globalThis.location?.search ?? "");
    const threadsOverride = Number(params.get("ortThreads"));
    ort.env.wasm.proxy = params.get("ortProxy") !== "0";
    ort.env.wasm.numThreads =
      threadsOverride > 0 ? threadsOverride : Math.min(4, navigator.hardwareConcurrency || 1);
    console.log(
      `[scan] ort init: numThreads ${ort.env.wasm.numThreads} proxy ${ort.env.wasm.proxy}` +
        ` crossOriginIsolated ${globalThis.crossOriginIsolated === true}`,
    );

    const model = await fetchWithProgress(
      modelUrl,
      (loaded, total) => progressListener?.(loaded, total),
      `could not load the encoder from ${modelUrl} (in dev, run: bun scripts/scan/export-index.ts)`,
    );
    const session = await ort.InferenceSession.create(model, {
      executionProviders: ["wasm"],
      // "basic" instead of the default "all": full graph optimization of the
      // fp16 model costs 3x fp32's create time (409 vs 137 ms on a desktop,
      // long enough to look like a hang on a 2016 phone) while "basic"
      // creates 4x cheaper with identical measured inference speed.
      graphOptimizationLevel: "basic",
    });

    // Self-benchmark: a small warmup batch, then one timed batch — enough to
    // estimate the per-image encoder cost that drives the slow-device
    // profile, cheap enough that a slow phone does not spend half its startup
    // benchmarking itself (the old 2x batch-16 bench cost 25 s on a Pixel 1).
    // Prints to the piped console so thread scaling can be read per device.
    // Batch 1 is timed separately: the session embeds candidates one at a
    // time, so the per-call overhead a single-image inference carries (proxy
    // round-trip, arena setup) is the number that decides whether candidates
    // are worth batching on a slow device.
    const warmupBatch = 2;
    const benchBatch = 4;
    for (const batch of [warmupBatch, benchBatch, 1]) {
      const benchInput = new Float32Array(batch * 3 * EMBED_IMAGE_SIZE * EMBED_IMAGE_SIZE);
      const benchStart = performance.now();
      await session.run({
        pixel_values: new ort.Tensor("float32", benchInput, [
          batch,
          3,
          EMBED_IMAGE_SIZE,
          EMBED_IMAGE_SIZE,
        ]),
      });
      const elapsed = performance.now() - benchStart;
      if (batch === benchBatch) {
        embedMsPerImage = elapsed / batch;
      }
      console.log(`[scan] ort bench: batch${batch} ${elapsed.toFixed(0)}ms`);
    }
    console.log(`[scan] ort bench: ~${embedMsPerImage.toFixed(0)}ms/image`);

    return async (pixels, count) => {
      // The staging tensor is sized for a full batch; a short final chunk must
      // be handed over trimmed or the shape and the data length disagree. This
      // must be a copy (`slice`), not a view: the proxy worker receives the
      // tensor via postMessage transfer, which detaches the underlying
      // ArrayBuffer — a subarray view would hand over (and kill) the session's
      // reusable staging buffer on the first frame.
      const slice = pixels.slice(0, count * 3 * EMBED_IMAGE_SIZE * EMBED_IMAGE_SIZE);
      const output = await session.run({
        pixel_values: new ort.Tensor("float32", slice, [
          count,
          3,
          EMBED_IMAGE_SIZE,
          EMBED_IMAGE_SIZE,
        ]),
      });
      return output.image_embeds.data as Float32Array;
    };
  })();
  try {
    return await cached;
  } catch (error) {
    // A failed forty-megabyte download must not poison the page until reload:
    // clear the slot so the next mount retries.
    cached = null;
    throw error;
  }
}
